### ISSUE TITLE
Some combinations of diameters/pitches don't work

### ISSUE THREAD

**Issue by jil24** [BalzGuenat/CustomThreads#2]
The way the threads are calculated results in some cases where internal threads have a pitch diameter that's smaller than their minor diameter, which isn't possible, for example, generating a M40x0.75 internal thread produces this XML:
```
<Thread>
        <Gender>internal</Gender>
        <Class>O.0</Class>
        <MajorDia>40.4</MajorDia>
        <PitchDia>39.23</PitchDia>
        <MinorDia>39.25</MinorDia>
        <TapDrill>39.25</TapDrill>
</Thread>
```

I used the descriptions on [this page](https://www.omnicalculator.com/construction/thread) to rewrite the calculations to give a basic set of diameters based on 6H/6g tolerances. For the O.0 offset, this now gives me results I expect, when I cross checked a couple of the more common sizes that appear in tables.

Here is the new threads function:
```python
    def threads(self, designation):
        ts = []
        for offset in self.offsets:
            offset_decimals = str(offset)[2:]  # skips the '0.' at the start
            depth = designation.depth()
            
            d = designation.size # basic major diameter AKA nominal diameter
            pitch = designation.pitch
            height = pitch*math.sqrt(3)/2 # height of the fundamental triangle
            d1 = d - (2*(5/8)*height) # basic minor diameter
            d2 = d - (2*(3/8)*height) # basic pitch diameter
            
            
            # some constants needed here, these are based on 6H/6g tolerances
            es = -(15+11*pitch)/1000 # fundamental deviation external
            EI = 0 # fundamental deviation internal - this would be (15+11*pitch)/1000 for the G position
            Td = 1*((180*math.pow(pitch,2/3))-(3.15*pow(pitch,-1/2)))/1000 # for tolerance grade 6
            Td2 = (90*math.pow(pitch,0.4)*math.pow(d,0.1))/1000 # for tolerance grade 6
            if (pitch < 1):
                TD1 =  (433*pitch-(190*math.pow(pitch,1.22)))/1000 # for tolerance grade 6
            else:
                TD1 =  (230*math.pow(pitch,0.7))/1000 # for tolerance grade 6
            TD2 = 1.32*(90*math.pow(pitch,0.4)*math.pow(d,0.1))/1000 # for tolerance grade 6
            Rmin = pitch/8
            y =  Rmin * (1-math.cos(math.pi/3-math.acos(1-Td2/(4*Rmin))))
            z = (height/4)+(Td2/2)-Rmin
            
            
            t = Thread()
            t.gender = "external"
            t.clazz = "O.{}".format(offset_decimals)
            t.majorDia = d + es - offset
            t.pitchDia = d2 + es - (Td2/2) - offset
            t.minorDia = d1 - es - y - z - offset
            ts.append(t)

            t = Thread()
            t.gender = "internal"
            t.clazz = "O.{}".format(offset_decimals)
            t.majorDia = d + EI + offset
            t.pitchDia = d2 + EI + (TD2/2) + offset
            t.minorDia = d1 + EI + (TD1/2) + offset
            t.tapDrill = d1 + EI + (TD1/2) + offset
            ts.append(t)
        return ts
```

**Comment by BalzGuenat** [comment]
Hey, thanks for your interest in the project!

I think I understand your issue on a technical level: The simplified way profiles are calculated can result in invalid geometry.
But I don't understand why this is an issue in a practical sense, at least for the use case targeted by this project.

As the README states, the generated threads are intended for 3D printing as an alternative to metric threads, which - especially at smaller diameters - are often too fine to print. The goal is *not* to generate arbitrary metric threads.

The case you describe uses a pitch of 0.75, which is quite fine, even for standard metric and thus not really suited for 3D printing IMHO.

If you are worried about this one case specifically, why not use standard ISO metric profiles that are already included in Fusion? If these are not sufficient and you want to generate arbitrary and accurate metric threads, my suggestion would be to fork this repo with a restated goal.

However, if this issue actually also exists for coarser threads (such that *would* be suitable for 3D printing), I would have to reevaluate.

**Comment by jil24** [comment]
That is perfectly understandable, since I'm doing something weird and ill-advised. Obviously printing such tiny threads is not something anyone wants to be doing if given a choice.

I am printing lens filter threads (typically metric 0.75mm pitch, with diameters of anywhere from 39-80mm). Since these have to interface with machined threads on lenses, it's useful to be able to vary an offset like you've implemented here, to compensate for the imprecision of FDM printers. Otherwise I end up using the stock Metric profile threads, like you suggested, and dilating/eroding the entire model in the slicer, which causes problems like weakening the walls elsewhere, or offsetting the thread faces manually in fusion360, which is clumsy and takes a while.

I am actually printing these on a stock Ender3 and the threads work reasonably well, once the proper offset has been dialed in. In my case, that is 0.2mm on internal threads, and 0.1 mm on external threads.

I do not have any evidence that this is messing with larger threads. The specific issue I identified only affects thread pitches of <= 0.8mm, so it would be totally fair to call that out of scope.

**Comment by BalzGuenat** [comment]
@jil24 hey could you please check out https://github.com/BalzGuenat/CustomThreads/pull/4 and leave some feedback, even if it's just a thumbs up?

**Comment by BalzGuenat** [comment]
closed with https://github.com/BalzGuenat/CustomThreads/pull/4
