### ISSUE TITLE
Smaller Diameter Profiles Please

### ISSUE THREAD

**Issue by MiscPrinter** [BalzGuenat/CustomThreads#5]
Awesome job. Thread have never been easier to print. 

Really liking the profiles but am running into times where smaller diameters are needed. As small as 3mm. Is it possible to add smaller diameters with an accompanying pitch decrease around 1.5-3mm?

**Comment by BalzGuenat** [comment]
I'm somewhat weary of supplying every conceivable thread configuration out of the box, as it's not an achievable goal.

Are you able to generate the threads you want yourself?

**Comment by berkeoznalbant** [comment]
Initially i had the same problem but changing the code allowed me to add any configuration I wanted.

**Comment by geekcouplettv** [comment]
The issue I am having i cannot generate any of file with main.py with python 3.12+
